INSERT INTO neighborhoods (id, neighborhood_name, description, top_attractions, photo_link)
VALUES
    (1,'NIEUWMARKET',
     'Nieuwmarkt offers a unique blend of historical charm, modern living, and a thriving social scene, making it a desirable area for both homeowners and investors alike.',
     'Central Station, Chinatown, De Waag, East India House Jacob Hooy,  Oude Kerk, Our Lord in the Attic, Montelbaanstoren, Red Light District,  Rembrandt House, Zuiderkerk',
    'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Nieuwmarkt.jpg'),
    (2,'MUSEUMPLEIN',
     'Museumkwartier (Museum Quarter) neighborhood is part of the Oud-Zuid district, one of the city''s most prestigious central neighborhoods, home to high-end shopping (P.C. Hooftstraat and Van Baerlestraat), the city''s biggest park and some of its best restaurants.',
     'Concertgebouw, Diamond Museum, Moco Museum, PC Hooftstraat, Rijksmuseum, Stedelijk Museum, Van Gogh Museum, Vondelpark, Zuiderbad',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Museumplein.jpg'),
    (3,'DE_WALLEN',
     'Wallen is the medieval city center, crossed by canals and narrow alleys lined with old-school bars. Surrounded by the neon-lit red-light district, the Oude Kerk is a centuries-old former church hosting cultural events.',
     'Chinatown, Convent of Bethany, De Koffieschenkerij, De Waag, East India, Nieuwmarkt, Our Lord in the Attic, Oude Kerk, Rembrandt House',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Wallen.jpg'),
    (4,'JORDAAN',
     'The Jordaan is one of Amsterdam’s most sought-after and picturesque neighborhoods, offering a blend of charming canals, historical buildings, and a lively, creative atmosphere.',
     'Anne Frank House, De 9 Straatjes, Hofjes, Lapjesmarkt, Maloe Melo, Noorderkerk, Noordermarkt, Pianola Museum, Slijterij De Ooievaar, Westerkerk',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Jordaan.jpg'),
    (5,'SPUI',
     'Spui is centrally located in Amsterdam Centrum, making it an ideal location for those who want to be close to the city’s most iconic attractions, restaurants, shopping, and cultural venues.',
     'Allard Pierson Museum, Amsterdam Museum, Begijnhof, Kalverstraat, Art Market, Book Market, Kooij, Flower Market',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spui.jpg'),
    (6,'SPIEGELBUURT',
     'The Spiegelbuurt is a trendy, charming, and increasingly desirable neighborhood located in Amsterdam’s city center, nestled between the famous Museumplein and De Pijp. Known for its peaceful residential atmosphere and close proximity to cultural landmarks, Spiegelbuurt offers a unique blend of quiet residential living and access to some of the city’s most iconic attractions.',
     'Canal Belt, Rijksmuseum, Museum Quarter, The Amsterdam City Archives, Spiegelkwartier',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spiegelbuurt.jpg'),
    (7,'DE_PLANTAGE',
     'De Plantage is one of Amsterdam’s most picturesque and serene neighborhoods, located just east of the city center. Known for its green spaces, historical buildings, and cultural institutions, De Plantage offers a peaceful residential experience while remaining close to the vibrant heart of Amsterdam.',
     'Hortus Botanicus, Artis Zoo, Oosterpark',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Plantage.jpg'),
    (8,'DE_PIJP',
     'De Pijp is one of Amsterdam’s most iconic and dynamic neighborhoods, known for its eclectic mix of cultures, vibrant street life, and artistic vibe. Located just south of the city center, De Pijp has evolved from a working-class area to one of the most sought-after places to live in the city.',
     'Albert Cuyp Market, Vondelpark, Museumplein, Sarphatipark',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Pijp.jpg'),
    (9,'LEIDSEPLEIN',
     'Leidseplein is one of Amsterdam’s most iconic and bustling squares, located just to the west of the city center. Known for its vibrant atmosphere, entertainment venues, and cultural landmarks, Leidseplein is a lively neighborhood that offers a perfect balance of modern city living with historic charm.',
     'Leidseplein Square, Royal Theatre Carré, Melkweg, Paradiso, Museumplein, Vondelpark',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Leidseplein.jpg'),
    (10,'IJ_WATERFRONT',
     'Centered on Centraal Station and stretching east and west along both banks of the River IJ, this fast-redeveloping area includes artificial islands, warehouses, and other installations of Amsterdam''s old harbor.',
     'NEMO Science Museum, Public Library (OBA), Scheepvaartmuseum, The Ravestijn Gallery, The Ravestijn Gallery, A''DAM Toren,Centraal Station',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/IJ+Waterfront.jpg'),
    (11,'REMBRANDTPLEIN',
     'The Rembrandtplein (Rembrandt Square) is one of Amsterdam''s most popular centres for nightlife and is known for its many cafés, terraces, clubs, and hotels. It mostly attracts rowdy Amsterdammers and out-of-towners.',
     'Rembrandt House Museum, Sarphatipark, Amstel River, Large statue of Rembrandt',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Rembrandtplein.jpg'),
    (12,'OUD_WEST',
     'The architecture of old storey houses and the monotonous and long rows of houses from the 19th century have now become a very popular neighborhood for urban living.',
     'Blue Boat Company, De Foodhallen, De Hallen, Hollandsche Manege, Leidseplein Ten Katemarkt, Vondelkerk, Vondelpark',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Oud-West.jpg'),
    (13,'OOST',
     'Amsterdam Oost (East) is one of the city’s most diverse, vibrant, and rapidly evolving neighborhoods. Known for its blend of cultural richness, green spaces, and contemporary developments, Oost offers a dynamic mix of residential living and lifestyle amenities.',
     'Artis, Bimhuis, Brouwerij ''t IJ, Muziekgebouw aan ''t IJ, Rembrandt Tower, The Whale, Tropenmuseum',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Oost.jpg'),
    (14,'SPAARNDAMMERBUURT',
     'The Spaarndammerbuurt is undergoing a major transformation, partly due to expensive new construction in the nearby Houthavens district. There used to be a lot of poverty and there were many neglected houses that were in serious disrepair. Many houses have now been redeveloped.',
     'Amsterdamse School, Het Schip, Jordaan, Theater Amsterdam, West District, Westergasfabriek, Westpoort',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spaarndammerbuurt.jpg'),
    (15,'RIVIERENBUURT',
     'Rivierenbuurt is a well-established, family-friendly neighborhood located in the South of Amsterdam. Known for its spacious residential properties, green spaces, and quiet, suburban atmosphere, this area offers a peaceful living environment while still being well-connected to the city’s vibrant core.',
     'Albert Cuyp Market, Amsterdams School, De Pijp, Parade, RAI Amsterdam, Zuidas',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Rivierenbuurt.jpg'),
    (16,'NOORD',
     'Amsterdam Noord is an up-and-coming, vibrant neighborhood located just across the IJ River from Amsterdam''s city center. Historically an industrial area, Noord has undergone a dramatic transformation in recent years, becoming one of the most exciting and sought-after districts in Amsterdam.',
     'A''DAM Toren, EYE, IJ Waterfront, NDSM',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Noord.jpg'),
    (17,'WESTPOORT',
     'Amsterdam Westpoort is a dynamic, industrial area located in the western part of the city, bordering Sloterdijk and Amsterdam West. Known primarily for its role as an industrial and logistical hub, Westpoort has gradually been evolving into a more mixed-use area, with a growing number of residential developments and increased interest from businesses and investors.',
     'Hempont ferry, Houthaven, Museum Het Schip, Port of Amsterdam, Ruigoord, Sloterdijk village, Spaarnwoude park, The New Kit, Westergasfabriek, Windmill ''De 1200 Roe',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Westpoort.jpg');
