INSERT INTO key_details (id, neighborhood_id, name, description)
VALUES
    (1,1,
     'Historic Market Square',
     'Nieuwmarkt is centered around a bustling square, historically known for its market, which is now home to cafés, shops, and restaurants, creating a vibrant local atmosphere.'),
    (2,1,
     'Cultural Hotspot',
     'The neighborhood is rich in history and culture.'),
    (3,1,
     'Great Connectivity',
     'Well-connected by public transportation, with the Nieuwmarkt Metro Station offering quick access to other areas of Amsterdam, making it ideal for both residents and commuters.'),
    (4,1,
     'Vibrant Local Scene',
     'The neighborhood is known for its trendy bars, cafés, and restaurants, as well as a lively community of locals, students, and expats. It’s a popular area for those who enjoy a lively yet laid-back atmosphere.'),
    (5,1,
     'Attractive Investment Potential',
     'With its proximity to the city center and ongoing development, Nieuwmarkt presents a strong opportunity for real estate investors looking for growth potential in a vibrant, central location.'),
    (6,2,
     'There is no key name yet(',
     'key details yet('),
    (7,3,
     'There is no key name yet(',
     'key details yet('),
    (8,4,
     'There is no key name yet(',
     'key details yet('),
    (9,5,
     'There is no key name yet(',
     'key details yet('),
    (10,6,
     'There is no key name yet(',
     'key details yet('),
    (11,7,
     'There is no key name yet(',
     'key details yet('),
    (12,8,
     'There is no key name yet(',
     'key details yet('),
    (13,9,
     'There is no key name yet(',
     'key details yet('),
    (14,10,
     'There is no key name yet(',
     'key details yet('),
    (15, 11,
     'There is no key name yet(',
     'key details yet('),
    (16,12,
     'There is no key name yet(',
     'key details yet('),
    (17,13,
     'There is no key name yet(',
     'key details yet('),
    (18,14,
     'There is no key name yet(',
     'key details yet('),
    (19,15,
     'There is no key name yet(',
     'key details yet('),
    (20,16,
     'There is no key name yet(',
     'key details yet('),
    (21,17,
     'There is no key name yet(',
     'key details yet(');