INSERT INTO neighborhoods (id, neighborhood_name, description, top_attractions, photo_link)
VALUES
    (1,'NIEUWMARKET',
     'Nieuwmarkt offers a unique blend of historical charm, modern living, and a thriving social scene, making it a desirable area for both homeowners and investors alike.',
     'Central Station, Chinatown, De Waag, East India House Jacob Hooy,  Oude Kerk, Our Lord in the Attic, Montelbaanstoren, Red Light District,  Rembrandt House, Zuiderkerk',
    'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Nieuwmarkt.jpg'),
    (2,'MUSEUMPLEIN',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Museumplein.jpg'),
    (3,'DE_WALLEN',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Wallen.jpg'),
    (4,'JORDAAN',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Jordaan.jpg'),
    (5,'SPUI',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spui.jpg'),
    (6,'SPIEGELBUURT',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spiegelbuurt.jpg'),
    (7,'DE_PLANTAGE',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Plantage.jpg'),
    (8,'DE_PIJP',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/De+Pijp.jpg'),
    (9,'LEIDSEPLEIN',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Leidseplein.jpg'),
    (10,'IJ_WATERFRONT',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/IJ+Waterfront.jpg'),
    (11,'REMBRANDTPLEIN',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Rembrandtplein.jpg'),
    (12,'OUD_WEST',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Oud-West.jpg'),
    (13,'OOST',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Oost.jpg'),
    (14,'SPAARNDAMMERBUURT',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Spaarndammerbuurt.jpg'),
    (15,'RIVIERENBUURT',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Rivierenbuurt.jpg'),
    (16,'NOORD',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Noord.jpg'),
    (17,'WESTPOORT',
     'There is no description yet(',
     'There is no attractions yet(',
     'https://smart-estate-backend.s3.eu-north-1.amazonaws.com/neighborhoods/Westpoort.jpg');
