INSERT INTO transport_details (id, transport_type, transport_numbers, neighborhood_id)
VALUES
    (1,'BUS',
     '51 53 54 Nieuwmarkt', 1),
    (2,'BUS',
    'There is no bus numbers yet(', 2),
    (3,'BUS',
     'There is no bus numbers yet(', 3),
    (4,'BUS',
     'There is no bus numbers yet(', 4),
    (5,'BUS',
     'There is no bus numbers yet(', 5),
    (6,'BUS',
     'There is no bus numbers yet(', 6),
    (7,'BUS',
     'There is no bus numbers yet(', 7),
    (8,'BUS',
     'There is no bus numbers yet(', 8),
    (9,'BUS',
     'There is no bus numbers yet(', 9),
    (10,'BUS',
     'There is no bus numbers yet(', 10),
    (11,'BUS',
     'There is no bus numbers yet(', 11),
    (12,'BUS',
     'There is no bus numbers yet(', 12),
    (13,'BUS',
     'There is no bus numbers yet(', 13),
    (14,'BUS',
     'There is no bus numbers yet(', 14),
    (15,'BUS',
     'There is no bus numbers yet(', 15),
    (16,'BUS',
     'There is no bus numbers yet(', 16),
    (17,'BUS',
     'There is no bus numbers yet(', 17);
