INSERT INTO key_details (id, neighborhood_id, name, description)
VALUES
    (1,1,
     'Historic Market Square',
     'Nieuwmarkt is centered around a bustling square, historically known for its market, which is now home to cafés, shops, and restaurants, creating a vibrant local atmosphere.'),
    (2,1,
     'Cultural Hotspot',
     'The neighborhood is rich in history and culture.'),
    (3,1,
     'Great Connectivity',
     'Well-connected by public transportation, with the Nieuwmarkt Metro Station offering quick access to other areas of Amsterdam, making it ideal for both residents and commuters.'),
    (4,1,
     'Vibrant Local Scene',
     'The neighborhood is known for its trendy bars, cafés, and restaurants, as well as a lively community of locals, students, and expats. It’s a popular area for those who enjoy a lively yet laid-back atmosphere.'),
    (5,1,
     'Attractive Investment Potential',
     'With its proximity to the city center and ongoing development, Nieuwmarkt presents a strong opportunity for real estate investors looking for growth potential in a vibrant, central location.'),
    (6,2,
     'There is no key name yet(',
     'key details yet('),
     (7,2,
     'There is no key name yet',
     'key details yet'),
     (7,2,
     'There is no key name yet',
     'key details yet'),
     (8,2,
     'There is no key name yet',
     'key details yet'),
     (9,2,
     'There is no key name yet',
     'key details yet'),
    (10,3,
     'Location',
     'De Wallen is centrally located in Amsterdam, surrounded by landmarks such as Dam Square, Nieuwmarkt, and the famous Red Light District canals. It offers easy access to public transport, including the Amsterdam Central Station, making it a highly sought-after area for both locals and visitors.'),
     (11,3,
     'Diverse Properties',
     'The neighborhood offers a range of real estate, from charming canal-side apartments and historic buildings to modern lofts and commercial spaces.'),
     (12,3,
     'History',
     'Medieval Roots: De Wallen dates back to the 14th century when it was a residential and commercial area. It became associated with prostitution around the 16th century.'),
     (13,3,
     'Safety and Crime',
     'While De Wallen is generally safe for tourists, it''s also an area where petty crime, such as pickpocketing, can occur. It''s always recommended to stay aware of your belongings.'),
     (14,3,
     'Unique Investment Opportunities',
     'De Wallen attracts tourists and business people alike, offering great potential for short-term rentals and commercial investments. With ongoing regulations and gentrification, the area has seen increased property values over the years. It’s ideal for those looking for properties with high rental yields or potential for future development.'),
    (15,4,
     'Location',
     'The Jordaan is located just a short walk from Amsterdam’s city center, with easy access to Dam Square, Anne Frank House, and the Nine Streets (De Negen Straatjes) — a popular shopping area. It’s perfectly positioned for both residents and tourists, offering a quieter residential experience without being far from major attractions.'),
    (16,4,
     'Diverse Properties',
     'The neighborhood offers a wide range of real estate options, including canal-side apartments, spacious townhouses, lofts, and studio apartments. Whether you''re looking for a home for yourself or an investment property, the Jordaan has something for every taste and budget.'),
    (17,4,
     'Artistic and Creative Vibe',
     'Once home to artists and writers, the Jordaan still maintains a creative energy, with numerous art galleries, independent boutiques, and vintage shops. It’s also known for its weekly markets, including the famous Noordermarkt flea market, where you can find antiques, local crafts, and fresh produce.'),
    (18,4,
     'Walkability',
     'Jordaan is a highly walkable area with many shops, parks, and public transport options within easy reach.'),
    (19,4,
     'Quiet Yet Central',
     'Although it’s an incredibly central location, the Jordaan retains a quieter, more relaxed atmosphere compared to the bustling areas around the Red Light District or Leidseplein. The residential streets offer a peaceful retreat, perfect for families, young professionals, and retirees alike.'),
    (20,5,
     'There is no key name yet',
     'key details yet'),
    (21,5,
     'There is no key name yet',
     'key details yet'),
    (22,5,
     'There is no key name yet',
     'key details yet'),
    (23,5,
     'There is no key name yet',
     'key details yet'),
    (24,5,
     'There is no key name yet',
     'key details yet'),
    (25,6,
     'Location',
     'Spiegelbuurt’s central location makes it perfect for people who want to enjoy the best of both worlds: a calm, neighborhood vibe while being close to everything Amsterdam has to offer. The neighborhood is within walking distance of Museumplein, Vondelpark, and De Pijp, offering quick access to museums, shops, restaurants, and more.'),
    (26,6,
     'Quiet Residential Atmosphere',
     'Unlike the hustle and bustle of Amsterdam’s more tourist-heavy areas, Spiegelbuurt offers a calm, peaceful environment with tree-lined streets and well-maintained buildings. This makes it an ideal spot for families, professionals, and anyone looking for a more relaxed, residential vibe while still being close to the city’s main attractions.'),
    (27,6,
     'Diverse Property Options',
     'Spiegelbuurt offers a variety of real estate options, from classic canal-side apartments and modern townhouses to charming 19th-century buildings. The area’s mix of traditional Dutch architecture and contemporary apartments provides a range of choices for potential buyers and renters, whether you’re seeking a historical home or a sleek modern apartment.'),
    (28,6,
     'Green Spaces',
     'In addition to Vondelpark, the area is surrounded by smaller parks and green spaces, making it perfect for those who appreciate outdoor living.'),
    (29,6,
     'Safe and Friendly',
     'The neighborhood is known for its low crime rate and strong sense of community. It’s a fantastic place for those who value safety and peace of mind in their living environment.'),
    (30,7,
     'Location',
     'De Plantage offers a central location just a short distance from the city center, making it easy to access major attractions like Dam Square, Leidseplein, and Jordaan.'),
    (31,7,
     'Green Spaces',
     'The neighborhood is known for its abundance of green spaces, including the iconic Hortus Botanicus (the botanical garden), Artis Zoo, and the Oosterpark. These tranquil areas provide a refreshing contrast to the bustling city center, offering residents plenty of opportunities for relaxation and outdoor activities.'),
    (32,7,
     'Historical Charm',
     'De Plantage is rich in history and boasts a mix of 19th-century buildings, canal houses, and modern residences. The area’s architecture is both charming and varied, featuring traditional Amsterdam homes and contemporary developments that cater to modern tastes.'),
    (33,7,
     'Cultural Institutions',
     'The neighborhood is home to several cultural landmarks, including the Hortus Botanicus, Artis Zoo, and the Royal Theatre Carre. The NEMO Science Museum and the Tropenmuseum (Tropical Museum) are also nearby, making De Plantage an attractive destination for both residents and visitors interested in science, culture, and nature.'),
    (34,8,
     'Location',
     'De Pijp is situated just south of the city center, offering easy access to major attractions like Museumplein, Vondelpark, and the Rijksmuseum. Its central location means you’re just minutes away from the heart of Amsterdam, yet it maintains a distinct local charm.'),
    (35,8,
     'Cultural Diversity',
     'Known for its multicultural atmosphere, De Pijp is home to a wide range of restaurants, cafes, and shops representing cuisines and cultures from around the world. The area’s diversity is one of its defining features, offering a unique, cosmopolitan living experience in Amsterdam.'),
    (36,8,
     'Vibrant Street Life',
     'De Pijp is one of Amsterdam’s most lively neighborhoods, with a wide variety of markets, festivals, and cultural events throughout the year. The Albert Cuyp Market, located in the heart of De Pijp, is one of the largest and most popular outdoor markets in Europe, attracting both locals and tourists.'),
    (37,8,
     'Eclectic Architecture',
     'The neighborhood features a mix of 19th-century townhouses, modern apartments, and historic canal houses. De Pijp is characterized by its narrow streets, charming buildings, and canals, offering a diverse range of properties, from classic Amsterdam homes to more contemporary, newly built spaces.'),
    (38,9,
     'Vibrant Entertainment District',
     'Leidseplein is famous for its entertainment venues, including theaters, bars, cafes, nightclubs, and live music venues. It’s a hotspot for nightlife, offering residents an abundance of dining, drinking, and entertainment options within walking distance.'),
    (39,9,
     'Cultural Landmarks',
     'Despite its lively nightlife, Leidseplein is also home to important cultural institutions, including the Rijksmuseum, Van Gogh Museum, and Stedelijk Museum, all located in the nearby Museumplein. The Royal Theatre Carré and Melkweg concert hall are located close by, offering a range of performances from opera to contemporary music.'),
    (40,9,
     'Accessibility',
     'Located just a short distance from Amsterdam''s city center, Leidseplein is exceptionally well-connected, making it a convenient area for commuting and getting around the city. Public transport options, including trams and metro stations, make traveling to other parts of Amsterdam and beyond very easy.'),
    (41,9,
     'Central Location',
     'Leidseplein’s location places it near some of Amsterdam’s best-known areas, including the Jordaan, Vondelpark, and Museumplein, making it an ideal neighborhood for those who want to live in the heart of the action yet still enjoy green spaces and cultural experiences.'),
    (42,10,
     'Prime Waterfront Location',
     'The IJ Waterfront stretches along the northern banks of the IJ River, offering residents breathtaking views of the water and the city skyline. The area provides easy access to the Amsterdam Central Station and is within walking distance of the city’s main attractions while still offering a more peaceful environment compared to the bustling city center.'),
    (43,10,
    'Urban Renewal and Modern Living',
    'What was once an industrial harbor has been transformed into a modern urban district. New residential developments, luxury apartments, office spaces, and cultural venues have all emerged along the water.'),
    (44,10,
    'Scenic Views and Outdoor Living',
    'The IJ River provides a picturesque backdrop to the IJ Waterfront, with many apartments offering panoramic water views. The area also boasts public parks, waterfront promenades, and bike paths, allowing residents to enjoy outdoor activities, strolls by the water, and easy access to green spaces.'),
    (45,10,
    'Proximity to the City Center',
    'The IJ Waterfront’s location just north of Amsterdam Central Station means it’s well-connected to the heart of the city. You can easily access key areas like Dam Square, Leidseplein, and Museumplein by ferry, metro, or tram. Despite being close to the city center, the waterfront offers a more serene and spacious environment, ideal for those seeking a quieter lifestyle with easy access to urban amenities.'),
    (46, 11,
     'Location',
     'Rembrandtplein offers easy access to major cultural landmarks, shopping streets, and the bustling city center. Its central location places residents at the very heart of Amsterdam''s activity.'),
    (47, 11,
     'Vibrant and Lively Atmosphere',
     'Rembrandtplein is one of the most energetic and dynamic areas in Amsterdam. The square is lined with cafes, bars, restaurants, and nightclubs, making it a popular spot for locals and tourists alike. The square’s outdoor terraces and art installations add to the lively and welcoming vibe of the area.'),
    (48, 11,
     'Cultural and Historical Significance',
     'Named after one of Amsterdam''s greatest artists, Rembrandtplein is not just about nightlife; it’s also home to historical landmarks and art. The square is close to several cultural sites, including the Rembrandt House Museum, which is dedicated to the life and works of the painter.'),
    (49, 11,
     'Green Spaces and Recreation',
     'While Rembrandtplein itself is a lively square, the neighborhood is also close to several green spaces, including the Amstel River and Sarphatipark, providing a perfect balance of urban living and outdoor recreation.'),
    (50,12,
     'Location',
     'Oud-West is bordered by the famous Vondelpark to the south, the bustling Jordaan district to the east, and the up-and-coming De Baarsjes area to the west. It is centrally located, offering easy access to public transportation, bike paths, and main roads, with a quick commute to the city center.'),
    (51,12,
     'Vibrant Local Life',
     'Oud-West is known for its lively and creative atmosphere. The area offers a mix of independent boutiques, trendy cafes, art galleries, and a wide range of restaurants serving both local and international cuisines. Popular streets like Kinkerstraat and De Clercqstraat are known for their vibrant shopping and dining scenes.'),
    (52,12,
     'Green Spaces',
     'The neighborhood is just south of the expansive Vondelpark, a green oasis perfect for outdoor activities, picnics, and cycling. There are also several smaller parks and green spaces scattered throughout Oud-West, offering residents plenty of opportunities to enjoy nature.'),
    (53,12,
     'Transportation',
     'Oud-West is well-connected to public transportation, including tram, bus, and metro lines. The Lelylaan station provides quick access to the Amsterdam Zuid business district and Schiphol Airport, while the Haarlemmerdijk area offers easy access to both trams and cycling routes.'),
    (54,12,
     'Community & Demographics',
     'Oud-West attracts a mix of professionals, young families, and creatives. The area is especially popular with expats due to its international vibe and proximity to work hubs and cultural attractions. The neighborhood has a diverse, young, and energetic feel, with a sense of community cultivated through local events and markets.'),
    (55,13,
     'Location',
     'Amsterdam Oost is located just east of the city center, bordered by the IJ River to the north, the Amstel River to the west, and the Oosterpark to the south. The area benefits from excellent transport connections to both the city center and other parts of Amsterdam, making it easy to commute while offering a quieter, more laid-back atmosphere compared to the city’s core.'),
    (56,13,
     'Cultural & Social Scene',
     'Amsterdam Oost is known for its cultural diversity and artistic vibe. The area features a mix of traditional Dutch culture, Mediterranean influences, and a growing international community. It''s home to a range of art galleries, cultural centers, and live music venues. The Tropenmuseum (Tropical Museum) and Oosterpark are key landmarks, while Indische Buurt offers trendy bars, cafes, and diverse ethnic cuisine.'),
    (57,13,
     'Green Spaces',
     'Oost is rich in green areas, with several large parks and outdoor spaces.'),
    (58,13,
     'Transportation',
     'The area is well-connected by public transport, including multiple tram and bus lines, metro stations (such as Weesperplein and Amstel Station), and easy access to major roads. Amsterdam Centraal is just a short metro ride away, making Oost an ideal location for those who need to commute to the city center or Schiphol Airport. Cycling is also a popular mode of transport in this neighborhood.'),
    (59,13,
     'Community & Demographics',
     'Oost attracts a diverse group of residents, from young professionals to families, artists, and students. The neighborhood''s mix of international cuisine, cultural venues, and community events fosters a lively and inclusive atmosphere. It''s a growing hub for creatives and entrepreneurs, with a strong focus on sustainability, diversity, and local initiatives.'),
    (60,14,
     'Location',
     'Spaarndammerbuurt is situated north of the well-known Haarlemmerdijk and Jordaan districts, and is bordered by the Westergasfabriek park to the west. It is close to the Sloterdijk station, providing quick access to the city center, Schiphol Airport, and other key parts of Amsterdam. The neighborhood is characterized by wide streets and a quiet, residential atmosphere, with easy access to shops, cultural venues, and public transport.'),
    (61,14,
     'Family-Friendly',
     'With its mix of residential properties and proximity to parks and schools, Spaarndammerbuurt is popular with families. The area offers good options for family homes and boasts a safe, quiet environment with ample green spaces for children to play.'),
    (62,14,
     'Green Spaces & Parks',
     'The neighborhood is close to Westergasfabriek, a large park and cultural complex that hosts events, markets, and festivals. Additionally, Noorderpark and Spaarndammerplantsoen are nearby, offering green spaces for outdoor activities.'),
    (63,14,
     'Transportation',
     'Spaarndammerbuurt has excellent public transport connections, with several tram lines and bus routes passing through the area. Sloterdijk Station provides direct access to trains and metro lines, making it easy to commute to Amsterdam Central, Schiphol Airport, or surrounding areas. Additionally, the area is well-connected by bike paths.'),
    (64,14,
     'Cultural & Social Scene',
     'While more residential than some of the other neighborhoods, Spaarndammerbuurt is not without its vibrant cultural spots. The Westergasfabriek cultural venue is a key focal point, with cinemas, cafes, restaurants, and event spaces. The Spaarndammerstraat has a mix of local shops, cafes, and restaurants that are gaining in popularity.'),
    (19,15,
     'There is no key name yet(',
     'key details yet('),
    (20,16,
     'There is no key name yet(',
     'key details yet('),
    (21,17,
     'There is no key name yet(',
     'key details yet(');